version: '2'
services:
    myaccount-app:
        image: myaccount
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myaccount-mysql:3306/myaccount?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=myaccount-elasticsearch:9300
        ports:
            - 8080:8080
    myaccount-mysql:
        extends:
            file: mysql.yml
            service: myaccount-mysql
    myaccount-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: myaccount-elasticsearch
